language: node_js
services: mongodb
node_js:
  - node
# before_script:
#   - sleep 15
#   - mongo netguru --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test -i --coverage
