version: "3"
services:
  web:
    build: .
    environment:
      - "MONGO_URI=mongodb://mongo:27017/netguru"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
